CSS Modifications
dinki/View-Assist pull request #26
Opened 2024-06-20 12:55 UTC by ADHDSquir

These changes fix some issues and may introduce others. There is still plenty more work to be done on the CSS but these commits should remove some unnecessary styles and make the core layout and clock work in either portrait or landscape. I want to get these changes in front of others for review before spending time on other views like the weather.

2024-06-21 14:33 UTC, dinki requested changes
This is a preference thing.  My preference is to have it display slightly off the bottom.  Can you make this a variable so user can define?  Default value would be the current position.

2024-06-21 17:19 UTC, ADHDSquir commented
> Re: affix assist to bottom of screen
> 
> This is a preference thing. My preference is to have it display slightly off the bottom. Can you make this a variable so user can define? Default value would be the current position.
> 
> I'm not sure how to make comments on individual items apparently.

The commit I just pushed should handle this while being backwards compatible.

2024-06-21 17:27 UTC, dinki commented
Apologies for not being clear.  The variable should be in the dashboard configuration like the weather entity.  I do not want to add this as a device specific setting.  The user can choose one setting to use across all devices for that dashboard.

2024-06-21 17:39 UTC, ADHDSquir commented
> Apologies for not being clear. The variable should be in the dashboard configuration like the weather entity. I do not want to add this as a device specific setting. The user can choose one setting to use across all devices for that dashboard.

Ah, that makes more sense. Moved it.

2024-06-24 18:51 UTC, jlmaners requested changes
I tested this and other than a one line issue in clock.yaml this looks good and works to make the display handle portrait and landscape better.

2024-06-24 18:51 UTC, jlmaners commented on View Assist dashboard and views/views/clock/clock.yaml
> +  time: '[[[ return variables.var_current_time ]]]'
Either line 69 or 70 needs to be removed as it is the same declaration and will cause the view to throw an error when trying to edit the card in the HA UI.

2024-06-24 18:51 UTC, jlmaners commented on View Assist device configuration/device_config_example.yaml
> +
Should consider removing this commit from the PR as it appears to be an extraneous line change

2024-06-26 12:46 UTC, dinki commented
@ADHDSquir 
Thanks for your work on this, it looks really great on the TSV and I'm happy to see that the dashboard icons on top right don't cause the weather data to move up and down.  Was that done by stretching the "title status" to two rows?  If so, I think this modification should be made in the dashboard so that all views can benefit.  Again, I am no CSS expert but it would be great to adjust the actual height of that row rather than add an additional row as that appears to be shifting the clock down a bit and it is appearing off center.

The view also looks great in portrait on the TSV and my phone.  Landscape on the phone does not show the date at all.  Can you try on your phone and see if you see the same?  

Can you test that the tap on weather navigates to the weather page?  For unknown reasons mine is not responding to the tap.  I just set this new dev environment up so it may just be a me problem.


I think the work in this PR is definitely a step in the right direction.  Would you mind considering making these changes and  the changes @jlmaners mention above in regards to the time declaration twice and the unnecessary change to the device configuration file?

Again, many thanks on your work on cleaning up my mess.

2024-08-14 13:58 UTC, dinki commented
Thanks for your submission and your patience.  Can you please submit this to branch viewassist-dashboard and we will work on things there.  Accepting to main with all these changes could pose problems.

2024-08-14 13:58 UTC, closed without merging